# Site settings
title: Archon Digital Labs
email: overlord@archon-digital.com
description: "An exercise on developing my own flat file CMS running on Jekyll, Foundation 5 and Liquid templating. I'll be publishing more information soon."
baseurl: ""
url: "http://archondigital.com"
username: archondigital
timezone: Asia/Manila

# Build settings
markdown: kramdown
permalink: pretty
