# Site settings
title: Archon Digital
email: overlord@archon-digital.com
description: "My personal blog. Covers most of what I do from web design to frontend development, gear, music and street photography. This site runs on Jekyll, Foundation 5 and Liquid templating."
baseurl: "http://archon.digital"
url: ""
username: archondigital
timezone: Asia/Manila
paginate: 12
paginate_path: "articles/:num"

# Build settings
markdown: kramdown
permalink: pretty

gems:
- jekyll-redirect-from
#   - jekyll-sitemap
